### ISSUE TITLE
Cleaning up new Hoodie’s core modules

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#436]
Hoodie is a server with a client API and an admin dashboard, which allows to build applications with front-end code only.

Each of these core components is an own npm module, and their naming is descriptive & clear.

```
hoodie
│
├─── hoodie-admin-dashboard
├─── hoodie-server
└─── hoodie-client
```

Hoodie’s core functionalities are:
1. Accounts
2. Data
3. Tasks

All three consist of both, a client and a server component. The names for these components are not coherent at this point, for example
- account-client
- hoodie-client-task-queue
- hapi-couchdb-task-api

We didn’t gave these names a lot of thought, and we tried to make clear that they are useful on themselves, not only in the context of Hoodie. I think we tried to achieve too much, and tried to solve problems we don’t have.

As far as I know, none of these modules are currently in use, so we can still fix this. Based on the discussion at https://github.com/hoodiehq/hoodie/pull/435, I’d suggest to use hoodie-server-\* and hoodie-client-\* prefixes for the respective sub components, meaning we would end up with

```
hoodie
│
├─── hoodie-admin-dashboard
│
├─┬─ hoodie-server
│ ├─── hoodie-server-account
│ ├─── hoodie-server-store
│ └─── hoodie-server-task
│
└─┬─ hoodie-client
  ├─── hoodie-client-log
  ├─── hoodie-client-connection-status
  ├─── hoodie-client-account
  ├─── hoodie-client-store
  └─── hoodie-client-task
```

To add to the confusion, we also have three modues that integrate the client & server modules for account, task & module. These are not used within Hoodie, and are meant to test the integrations in isolation. They might be useful for people who only need e.g. the store functionality of Hoodie, but again, this is not a problem that we have at the moment. Currently these modules are called 
- hapi-couchdb-account
- hapi-couchdb-store
- hapi-couchdb-task

I’d suggest to rename them to something that makes clear that they are not used in Hoodie. My suggestion would be 
- hoodie-standalone-account
- hoodie-standalone-store
- hoodie-standalone-task

We could also move these out of the `hoodiehq` organisation, to farther reduce confusion, especially towards new contributors.
### Account
- [x] rename https://github.com/hoodiehq/hapi-couchdb-account to hoodie-standalone-account
- [x] deprecate https://www.npmjs.com/package/hapi-couchdb-account
- [x] rename https://github.com/hoodiehq/hapi-couchdb-account-api to hoodie-server-account
- [x] deprecate https://www.npmjs.com/package/hapi-couchdb-account-api
- [x] publish hoodie-server-account@1.0.0
- [x] rename https://github.com/hoodiehq/account-client to hoodie-client-account
- [x] deprecate https://www.npmjs.com/package/account-client
- [x] publish hoodie-client-account@1.0.0
- [x] update dependencies in https://github.com/hoodiehq/hoodie-standalone-account
- [x] update https://github.com/hoodiehq/hoodie-client/blob/master/package.json
- [x] update https://github.com/hoodiehq/hoodie-server/blob/next/package.json
### Store
- [x] rename https://github.com/hoodiehq/hapi-couchdb-store to hoodie-standalone-store
- [x] deprecateed https://www.npmjs.com/package/hapi-couchdb-store
- [x] rename https://github.com/hoodiehq/hapi-couchdb-store-api to hoodie-server-store
- [x] hapi-couchdb-account-api was not published on npm
- [x] publish hoodie-server-store@1.0.0
- [x] rename https://github.com/hoodiehq/pouchdb-hoodie-store to hoodie-client-store
- [x] deprecate https://www.npmjs.com/package/pouchdb-hoodie-store
- [x] publish hoodie-client-store@1.0.0
- [x] update dependencies in https://github.com/hoodiehq/hoodie-standalone-store
- [x] update https://github.com/hoodiehq/hoodie-client/blob/master/package.json
- [x] update https://github.com/hoodiehq/hoodie-server/blob/next/package.json
### Task
- [x] rename https://github.com/hoodiehq/hoodie-client-task-queue to hoodie-client-task
- [x] deprecate https://www.npmjs.com/package/hoodie-client-task-queue
- [x] publish hoodie-client-task@1.0.0
- [x] rename https://github.com/hoodiehq/hapi-couchdb-task to hoodie-standalone-task
- [x] extract server logic from hoodie-standalone-task into hoodie-server-task
- [x] hapi-couchdb-task was not yet published on npm, so nothing to do here
- [x] update dependencies in https://github.com/hoodiehq/hoodie-standalone-task
- [x] update https://github.com/hoodiehq/hoodie-client/blob/master/package.json
- [x] update https://github.com/hoodiehq/hoodie-server/blob/next/package.json
### Others
- [ ] update references at http://gr2m.github.io/milestones/
- [x] fix references in https://github.com/hoodiehq/hoodie-client
- [x] fix references in https://github.com/hoodiehq/hoodie-server
- [x] update https://github.com/hoodiehq/hoodie/pull/435
### Later
- [ ] unpublish https://www.npmjs.com/package/hapi-couchdb-account
- [ ] unpublish https://www.npmjs.com/package/hapi-couchdb-account-api
- [ ] unpublish https://www.npmjs.com/package/account-client
- [ ] unpublish https://www.npmjs.com/package/hapi-couchdb-store
- [ ] unpublish https://www.npmjs.com/package/pouchdb-hoodie-store
- [ ] unpublish https://www.npmjs.com/package/hoodie-client-task-queue

**Comment by simonv3** [comment]
@gr2m asked for some outsider feedback in Slack, here it is:

I am confused about what all the different things do. I've worked with the "current" version of Hoodie (pre-1.0 I guess?) and get what the admin dashboard does and the difference between the server and the client. After reading this I'm not quite sure how accounts / data / and tasks are "core functionality" (do you just mean 'storing data' is core functionality?), but the way you've named and organized it makes sense. My one question is why admin dashboard doesn't get split across server and client either? Does it fall outside of that divide?

My feedback on the name cleanup issue - I’m not sure what this set of modules do (`hapi-couchdb-account`, `hapi-couchdb-store`, `hapi-couchdb-task`), but I feel like renaming them to have hoodie in the name if they’re not used in hoodie is a bit confusing? It might help if they weren’t in the organization, true.

There you go - I'm not sure how helpful that is. I may have completely missed the point!

**Comment by gr2m** [comment]
Thanks @simonv3, that's very helpful!

**Comment by timblack1** [comment]
I think the hoodie-server-\* and hoodie-client-\* naming scheme is very helpful.  I haven't had time to jump into helping write the PouchDB version of Hoodie, but one thing that made it hard to know how I could help if I had the time was that the "old" or "current" naming scheme made it hard to understand how all the modules are intended to fit together.

**Comment by gr2m** [comment]
All right, I'll go ahead and make the changes now, thanks for your inputs. But just in case you have good arguments to change the naming, I don't mind doing it again if it's good for the community, I'm just rushing a little as we will start an outreach tomorrow, and I feel like these naming changes would make things more approachable and clear to new contributors

**Comment by gr2m** [comment]
Okay, I got the most work done. The hoodie-_-task modules are not yet ready for prime time, they need some work to adapt it how the hoodie-_-store modules are done. And we should review the READMEs.

But I hope the new naming is clearer now

**Comment by varjmes** [comment]
_pokes head in_
I think this is the first step in me starting to understand the Hoodie Infrastructure. Thank you so much.

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie/pull/435. But please create follow up issues if you have any farther suggestions :)
